Fix regression introduced by 99df7a3
There wasn't a need for the check added

Traceback shown in logs;

Traceback (most recent call last):
  File "/home/ibiam/Activities/irc-activity/purk/widgets.py", line 601, in hover
    if not hover_iter.ends_line():
AttributeError: 'bool' object has no attribute 'ends_line'

Signed-off-by: Ibiam Chihurumnaya <ibiamchihurumnaya@gmail.com>